# Generated by Django 4.1.5 on 2023-01-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='image_url',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/c/ce/7-11_selling_all_kinds_of_snacks_in_Taiwan.jpg'),
        ),
    ]
